#desc "One line task description"
#task :name_of_task do
#  puts "I am rake"
#end

#desc "First task description"
#task :first_task do
#  puts "I am first rake"
#end
#
desc "Second task description"
task :second_task do
  puts "I am second rake"
end
#
#desc "Example of a task with prerequisites"
#task :third_task => ["first_task", "second_task"] do
#  puts "I am dependent task"
#end
#
#desc "Example of task with parameters and prerequisites"
#task :my_task, [:first_arg, :second_arg] => ["first_task", "second_task"] do |t, args|
#  args.with_defaults(:first_arg => "Foo", :last_arg => "Bar")
#  puts "First argument was: #{args.first_arg}"
#  puts "Second argument was: #{args.second_arg}"
#end
#
#task :default => ["third_task"]

#desc "Example of task with invoke"
#task :first_task do
#  Rake::Task[:second_task].invoke
#end

file 'mydoc.pdf' => ['mydoc.xml', 'mydoc.xslt'] do
 puts "I am doc"
end